# Generated by Django 4.2.23 on 2025-10-25 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                ("login_time", models.DateTimeField()),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance",
                "db_table": "attendance",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("customer_code", models.CharField(max_length=50, unique=True)),
                ("full_name", models.CharField(max_length=150)),
                ("nickname", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=120, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "aadhar_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("documents_url", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customers",
            },
        ),
        migrations.CreateModel(
            name="DailyCollection",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("collection_date", models.DateField()),
                ("agent_id", models.BigIntegerField()),
                (
                    "cash_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "upi_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "card_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
            options={
                "verbose_name": "Daily Collection",
                "verbose_name_plural": "Daily Collections",
                "db_table": "daily_collections",
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("loan_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_due_count", models.IntegerField()),
                ("due_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "interest_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "repayment_mode",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "loan_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("defaulted", "Defaulted"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_by", models.BigIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="myapp.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
                "db_table": "loans",
            },
        ),
        migrations.CreateModel(
            name="LoanType",
            fields=[
                (
                    "loan_type_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Loan Type",
                "verbose_name_plural": "Loan Types",
                "db_table": "loan_types",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("user_id", models.BigIntegerField()),
                ("title", models.CharField(max_length=150)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
            },
        ),
        migrations.CreateModel(
            name="LoanDue",
            fields=[
                ("due_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("due_number", models.IntegerField()),
                ("due_date", models.DateField()),
                ("due_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[("cash", "Cash"), ("upi", "UPI"), ("card", "Card")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("collected_by", models.BigIntegerField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("skip_reason", models.TextField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dues",
                        to="myapp.loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Due",
                "verbose_name_plural": "Loan Dues",
                "db_table": "loan_dues",
            },
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.loantype",
            ),
        ),
    ]
