# Generated by Django 4.2.23 on 2025-10-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_attendance_customer_dailycollection_loan_loantype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installment_no", models.PositiveIntegerField()),
                ("due_date", models.DateField()),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "interest_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_due", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "remaining_principal",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="myapp.loan",
                    ),
                ),
            ],
            options={
                "db_table": "loan_schedule",
                "ordering": ["installment_no"],
            },
        ),
    ]
