# Generated by Django 4.2.23 on 2025-10-27 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_loanschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanschedule",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "collection_agent"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
