# Generated by Django 4.2.23 on 2025-10-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_loanschedule_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanschedule",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("done", "Done")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
